name: Reusable Release Workflow

on:
  workflow_call:
    inputs:
      fmt_status:
        required: false
        type: string
        default: 'clean'
    secrets:
      TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release (patch, minor, major)'
        required: false
        type: choice
        options:
          - ''
          - 'patch'
          - 'minor'
          - 'major'
        default: ''

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6.0.0
        with:
          github-token: ${{ github.event_name == 'workflow_dispatch' && secrets.GITHUB_TOKEN || secrets.TOKEN }}
          skip-version-file: true

      - name: create release for workflow_call
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'workflow_call' && steps.changelog.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.TOKEN }}
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ inputs.fmt_status == 'needs-formatting' && '[FMT NEEDED] ' || '' }}${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          updateOnlyUnreleased: true
          allowUpdates: true
          skipIfReleaseExists: true

      - name: create manual release
        uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'workflow_dispatch' && (steps.changelog.outputs.skipped == 'false' || inputs.release_type != '') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          updateOnlyUnreleased: true
          allowUpdates: true
          skipIfReleaseExists: true
