name: Terraform Validation
on:
  pull_request:

  push:

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.release.outputs.should_release }}
    steps:
      - uses: actions/checkout@v4
      - id: release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "should_release=true" >> $GITHUB_OUTPUT

  validate-modules:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"
      - name: Terraform Init
        working-directory: examples/basic-usage
        run: terraform init -backend=false
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -no-color -out=tfplan

  trigger-release:
    needs: [changes, validate-modules]
    if : ${{ needs.changes.outputs.should_release == 'true' }}
    uses: ./.github/workflows/release.yml
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
